services:
  - type: web
    name: pear
    env: node
    buildCommand: npm --prefix frontend install --include=dev && npm --prefix frontend run build && npm --prefix server install && npm --prefix server run migrate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
